export const environment = {
  production: true,
  loginUrl: 'http://devicepe.com/authenticate',
  brandUrl:'http://devicepe.com/devicePe-ws/v1/brands/find/all',
  brandSaveUrl:'http://devicepe.com/devicePe-ws/v1/brands/save',
  brandUpdateUrl:'http://devicepe.com/devicePe-ws/v1/brands/update',
  accessoriesUrl:'http://devicepe.com/devicePe-ws/v1/accessories/find/all',
  accessoriesUpdateUrl:'http://devicepe.com/devicePe-ws/v1/accessories/update',
  modelsUrl:'http://devicepe.com/devicePe-ws/v1/models/find/all',
  modelsUpdateUrl:'http://devicepe.com/devicePe-ws/v1/models/update',
  varientsUrl:'http://devicepe.com/devicePe-ws/v1/varients/find/all',
  varientsUpdateUrl:'http://devicepe.com/devicePe-ws/v1/varients/update',
  varientsCheckListUrl:'http://devicepe.com/devicePe-ws/v1/varients/checklst/find/all',
  varientsCheckListUpdateUrl:'http://devicepe.com/devicePe-ws/v1/varients/checklst/update',
  bulkUploadUrl:'http://devicepe.com/devicePe-ws/v1/devices/import',
  otpValidateUrl:'http://devicepe.com/notification-ws/v1/otp/validate',
  registerUrl:'http://devicepe.com/user-ws/v1/register',
  resendOtpUrl:'http://devicepe.com/notification-ws/v1/otp/resend',
  fileUploadUrl:'http://devicepe.com/fileuploader-ws/v1/upload'
};
