export const environment = {
  production: true,
  loginUrl: 'http://devicepe.com:6090/authenticate',
  brandUrl:'http://devicepe.com:6090/devicePe-ws/v1/brands/find/all',
  brandSaveUrl:'http://devicepe.com:6090/devicePe-ws/v1/brands/save',
  brandUpdateUrl:'http://devicepe.com:6090/devicePe-ws/v1/brands/update',
  accessoriesUrl:'http://devicepe.com:6090/devicePe-ws/v1/accessories/find/all',
  accessoriesUpdateUrl:'http://devicepe.com:6090/devicePe-ws/v1/accessories/update',
  modelsUrl:'http://devicepe.com:6090/devicePe-ws/v1/models/find/all',
  modelsUpdateUrl:'http://devicepe.com:6090/devicePe-ws/v1/models/update',
  varientsUrl:'http://devicepe.com:6090/devicePe-ws/v1/varients/find/all',
  varientsUpdateUrl:'http://devicepe.com:6090/devicePe-ws/v1/varients/update',
  varientsCheckListUrl:'http://devicepe.com:6090/devicePe-ws/v1/varients/checklst/find/all',
  varientsCheckListUpdateUrl:'http://devicepe.com:6090/devicePe-ws/v1/varients/checklst/update',
  bulkUploadUrl:'http://devicepe.com:6090/devicePe-ws/v1/devices/import',
  otpValidateUrl:'http://devicepe.com:6090/notification-ws/v1/otp/validate',
  registerUrl:'http://devicepe.com:6090/user-ws/v1/register',
  resendOtpUrl:'http://devicepe.com:6090/notification-ws/v1/otp/resend',
  fileUploadUrl:'http://devicepe.com:6090/fileuploader-ws/v1/upload',
  ordersUrl:'http://devicepe.com:6090/devicePe-ws/v1/orders/all',
};
